// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversation usize <-> uintptr_t is wrong");
extern "C" {
#endif

    typedef struct LockedWalletOpaque LockedWalletOpaque;


    LockedWalletOpaque *LockedWallet_new(struct CRustStrView a0, struct CRustSliceu8 a1);

    struct CRustResult4232mut3232c_voidCRustString LockedWallet_unlock(const LockedWalletOpaque * const self, struct CRustSliceu8 a0);

    void LockedWallet_delete(const LockedWalletOpaque *self);

#ifdef __cplusplus
}
#endif

