// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversation usize <-> uintptr_t is wrong");
extern "C" {
#endif

    typedef struct UnlockedWalletOpaque UnlockedWalletOpaque;


    UnlockedWalletOpaque *UnlockedWallet_new(struct CRustStrView a0);

    struct CRustResult4232mut3232c_voidCRustString UnlockedWallet_lock(const UnlockedWalletOpaque * const self, struct CRustSliceu8 a0);

    void UnlockedWallet_delete(const UnlockedWalletOpaque *self);

#ifdef __cplusplus
}
#endif

