// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversation usize <-> uintptr_t is wrong");
#endif
            #include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceu8 {
    const uint8_t * data;
    uintptr_t len;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_slice_tmpl.hpp"
#endif
