// Automatically generated by flapigen
#pragma once

namespace rust {
template<bool>
class LockedWalletWrapper;
using LockedWallet = LockedWalletWrapper<true>;
using LockedWalletRef = LockedWalletWrapper<false>;
} // namespace rust
