// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include "rust_str.h"
#include <string_view>
#include <stdint.h>
#include "CRustSliceu8.h"
#include "LockedWallet.hpp"
#include "c_LockedWallet.h"
#include "rust_result4232mut3232c_voidCRustString.h"
#include <variant>

#include "c_UnlockedWallet.h"

namespace rust {

template<bool>
class UnlockedWalletWrapper;
using UnlockedWallet = UnlockedWalletWrapper<true>;
using UnlockedWalletRef = UnlockedWalletWrapper<false>;


template<bool OWN_DATA>
class UnlockedWalletWrapper {
public:
    using value_type = UnlockedWalletWrapper<true>;
    friend class UnlockedWalletWrapper<true>;
    friend class UnlockedWalletWrapper<false>;

    using SelfType = typename std::conditional<OWN_DATA, UnlockedWalletOpaque *, const UnlockedWalletOpaque *>::type;
    using CForeignType = UnlockedWalletOpaque;

    UnlockedWalletWrapper(UnlockedWalletWrapper &&o) noexcept: self_(o.self_)
    {
        o.self_ = nullptr;
    }
    UnlockedWalletWrapper &operator=(UnlockedWalletWrapper &&o) noexcept
    {
        assert(this != &o);
        free_mem(this->self_);
        self_ = o.self_;
        o.self_ = nullptr;
        return *this;
    }
    explicit UnlockedWalletWrapper(SelfType o) noexcept: self_(o) {}
    UnlockedWalletOpaque *release() noexcept
    {
        UnlockedWalletOpaque *ret = self_;
        self_ = nullptr;
        return ret;
    }
    explicit operator SelfType() const noexcept { return self_; }
    UnlockedWalletWrapper<false> as_rref() const noexcept { return UnlockedWalletWrapper<false>{ self_ }; }
    const UnlockedWalletWrapper<true> &as_cref() const noexcept { return reinterpret_cast<const UnlockedWalletWrapper<true> &>(*this); }

    UnlockedWalletWrapper(const UnlockedWalletWrapper&) = delete;
    UnlockedWalletWrapper &operator=(const UnlockedWalletWrapper&) = delete;

    UnlockedWalletWrapper(std::string_view a0) noexcept
    {

        this->self_ = UnlockedWallet_new(CRustStrView{ a0.data(), a0.size() });
        if (this->self_ == nullptr) {
            std::abort();
        }
    }

    std::variant<LockedWallet, RustString> lock(RustSlice<const uint8_t> a0) const noexcept;

private:
   static void free_mem(SelfType &p) noexcept
   {
        if (OWN_DATA && p != nullptr) {
            UnlockedWallet_delete(p);
        }
        p = nullptr;
   }
public:
    ~UnlockedWalletWrapper() noexcept
    {
        free_mem(this->self_);
    }

private:
    SelfType self_;
};


    template<bool OWN_DATA>
    inline std::variant<LockedWallet, RustString> UnlockedWalletWrapper<OWN_DATA>::lock(RustSlice<const uint8_t> a0) const noexcept
    {

        struct CRustResult4232mut3232c_voidCRustString ret = UnlockedWallet_lock(this->self_, a0.as_c<CRustSliceu8>());
        return ret.is_ok != 0 ?
              std::variant<LockedWallet, RustString> { LockedWallet(static_cast<LockedWalletOpaque *>(ret.data.ok)) } :
              std::variant<LockedWallet, RustString> { RustString{ret.data.err} };
    }

} // namespace rust
