// Automatically generated by flapigen
#pragma once

namespace rust {
template<bool>
class UnlockedWalletWrapper;
using UnlockedWallet = UnlockedWalletWrapper<true>;
using UnlockedWalletRef = UnlockedWalletWrapper<false>;
} // namespace rust
